name: Delopyment

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy App on Server
        uses: actions/checkout@v2
        with:
          host: ${{secrets.SSH_HOST}}
          port: ${{secrets.SSH_PORT}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            whoami
            echo 'Change of directory'
            cd /var/www/revicit2.0
            echo 'Pull code'
            git pull origin dev
            composer install --no-interaction --prefer-dist --optimize-autoloader
            cp /var/www/envs/revicit2.0/staging.env /var/www/revicit2.0/.env
            chown -R www-data:www-data ./storage/
            php artisan key:generate
            php artisan migrate --force
            php artisan queue:restart
            php artisan optimize:clear
            php artisan db:seed
            echo 'Done with deployment'
            php artisan schedule:run
            echo 'Scheduler running'



